### ISSUE TITLE
Unrecoverable error when analyzing dependencies

### ISSUE THREAD

**Issue by umpirsky** [schmittjoh/php-code-analysis#13]
[Review](http://jmsyst.com/reviews/e9b33bca-06eb-487e-8386-89ba721b72a7) failed for [zymfony-validator](https://github.com/umpirsky/zymfony-validator):

```
Package is being installed.
Package has been installed.
Dependencies are being installed.
Oops, an internal error occurred.
Package is being installed.
Package has been installed.
Dependencies are being installed.
Oops, an internal error occurred.
Package is being installed.
Package has been installed.
Dependencies are being installed.
Oops, an internal error occurred.
Package is being installed.
Package has been installed.
Dependencies are being installed.
Oops, an internal error occurred.
It seems like there was an unrecoverable error when analyzing your dependencies. Please check your composer.json.
```

I can't find any issues with my compose.json.

**Comment by schmittjoh** [comment]
Could you add the link the review? This would make it easier to find it.

**Comment by umpirsky** [comment]
@schmittjoh Issue updated.

**Comment by schmittjoh** [comment]
Thanks.

The issue was that the "intl" extension was not installed on the VM which does the composer installs. Unfortunately, composer does not allow to turn this off yet (see composer/composer#1171), but I have installed a few extensions (including the intl extension) as a temporary workaround on the VM.
