### ISSUE TITLE
Each reviews fails for some reasons (Composer) ?

### ISSUE THREAD

**Issue by Taluu** [schmittjoh/php-code-analysis#37]
Hi,

Here is my build : http://jmsyst.com/reviews/cbc97dc1-0feb-4b2a-aec7-2f3f075290d3 (you may check the other ones), and it is always the same error : composer does not seem to be able to resolve the packages.

OK, that's fine, but when i'm doing these commands (with an updated composer), it just works, all the packages are installed... ?

Thanks. :)

**Comment by schmittjoh** [comment]
Hey,

I've checked this, and basically it is due to your requirement on PHP 5.4.
The VM which does run the installation through composer has only 5.3
installed, and composer itself does not provide an option to turn checks
for environment packages (like PHP, or PHP extensions) off.

I'll research whether we can modify composer to allow this, but at least
you know why it failed for now :)

**Comment by daviddesberg** [comment]
I'm having the same issue for the same reason (5.4 dependency) (:

**Comment by schmittjoh** [comment]
I'm working with Jordi on it, current issue is at composer/composer#1468

**Comment by schmittjoh** [comment]
As a temporary workaround, I've installed a couple of additional PHP extensions on the VMs so that you should not see it that often anymore.
