### ISSUE TITLE
Unrecoverable error when analyzing dependencies

### ISSUE THREAD

**Issue by fabstei** [schmittjoh/php-code-analysis#40]
Hey,

there seems to be wrong something with my composer dependencies but I have no clue to what it could be. Local install/update (cli) works.

Review: [fabstei/shorturl-bundle](http://jmsyst.com/reviews/6b2f79eb-9b6e-474a-a93e-27b18ea891cb)

The log it produces:

```
Package is being installed.
Package has been installed.
Dependencies are being installed.
Dependencies have been installed.
Scanning Package twig/twig (dev-master).
[...]
Scanning Package fabstei/shorturl-bundle ().
It seems like there was an unrecoverable error when analyzing your dependencies. This could be a problem with your composer.json, but might also be an internal error.
```

Thanks for the great tool (even though I couldn't get to work it for me, yet), excellent contribution!

**Comment by schmittjoh** [comment]
There was an error because you have a property on an interface (UserInterface) which the code did not really handle gracefully. I've patched this case now, and once its deployed it should work.

However, you'll probably want to remove the property from the interface anyway as it would produce a runtime error.

**Comment by fabstei** [comment]
Thanks!
